# Generated by Django 4.2.6 on 2023-10-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodification',
            name='images',
        ),
        migrations.AddField(
            model_name='productmodification',
            name='images',
            field=models.ManyToManyField(blank=True, to='catalog.image', verbose_name='Изображения'),
        ),
    ]
