# Generated by Django 4.2.6 on 2023-11-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodification',
            name='is_sale',
        ),
    ]
