# Generated by Django 4.2.6 on 2023-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productmodification_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.AddField(
            model_name='productmodification',
            name='Attachment',
            field=models.ManyToManyField(blank=True, to='catalog.attachment', verbose_name='Прикрепленные'),
        ),
    ]
