# Generated by Django 4.2.6 on 2023-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productmodification_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodification',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
    ]
