# Generated by Django 4.2.6 on 2023-10-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_productmodification_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodification',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='productModification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.productmodification'),
            preserve_default=False,
        ),
    ]
