# Generated by Django 4.2.6 on 2023-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Старая цена'),
        ),
    ]
