# Generated by Django 4.2.6 on 2023-10-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productmodification_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='productModification',
            new_name='product_modification',
        ),
    ]
