# Generated by Django 4.2.6 on 2023-10-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_productmodification_image_product_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_modification',
        ),
        migrations.AddField(
            model_name='productmodification',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.image'),
            preserve_default=False,
        ),
    ]
