# Generated by Django 4.2.6 on 2023-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_productmodification_images_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodification',
            name='modifications_images',
            field=models.ManyToManyField(blank=True, to='catalog.image', verbose_name='Изображения'),
        ),
    ]
