# Generated by Django 4.2.6 on 2023-12-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AddField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
