# Generated by Django 4.2.6 on 2023-10-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productmodification_modifications_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='original_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Изображения', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productmodification',
            name='modifications_images',
            field=models.ManyToManyField(blank=True, to='catalog.image', verbose_name='Изображения комплектаций'),
        ),
    ]
