# Generated by Django 4.2.6 on 2024-01-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_image_options_image_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='my_order',
            new_name='order',
        ),
    ]
