# Generated by Django 4.2.6 on 2023-10-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_images_image_original_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_image',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Оригинальное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Изображения', to='catalog.product', verbose_name='Изображение для товара'),
        ),
    ]
