# Generated by Django 4.2.6 on 2023-10-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_image_options_remove_image_original_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='path',
        ),
    ]
