# Generated by Django 4.2.6 on 2024-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_image_options_rename_my_order_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rz_id',
            field=models.IntegerField(default=0, verbose_name='ID категории на Rozetka'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
