# Generated by Django 4.2.6 on 2024-02-07 06:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_category_rz_id_alter_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='size',
            name='name_ru',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='name_uk',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
