# Generated by Django 4.2.6 on 2024-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_blogpost_content_ru_blogpost_content_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_locality',
            field=models.TextField(blank=True, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_post_office',
            field=models.TextField(blank=True, null=True, verbose_name='Отделение доставки'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_service',
            field=models.CharField(blank=True, choices=[('nova_poshta', 'Новая почта'), ('ukr_poshta', 'Укрпочта')], max_length=20, null=True, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='sale',
            name='prepayment',
            field=models.CharField(blank=True, choices=[('prepayment_150', 'Предоплата 150 грн.'), ('prepayment_full', 'Полная предоплата')], max_length=20, null=True, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_email',
            field=models.TextField(blank=True, null=True, verbose_name='Email пользователя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_surname',
            field=models.TextField(blank=True, null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_telephone',
            field=models.TextField(blank=True, null=True, verbose_name='Отделение доставки'),
        ),
    ]
