# Generated by Django 4.2.6 on 2024-02-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_sale_delivery_locality_sale_delivery_post_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='messengers',
            field=models.JSONField(default=list, verbose_name='Мессенджеры'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_telephone',
            field=models.TextField(blank=True, null=True, verbose_name='Телефон пользователя'),
        ),
    ]
