# Generated by Django 4.2.6 on 2024-03-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_sale_delivery_locality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productmodification',
            name='updated_at',
        ),
    ]
