# Generated by Django 4.2.6 on 2024-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_productmodification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_method', models.CharField(max_length=20, verbose_name='Связь с клиентом')),
                ('delivery_method', models.CharField(max_length=20, verbose_name='Способ доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('post_office', models.CharField(max_length=100, verbose_name='Отделение почты')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
