# Generated by Django 4.2.6 on 2024-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_modifications',
            field=models.ManyToManyField(blank=True, to='catalog.productmodification', verbose_name='Модификации товара'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('telegram', 'telegram')], default='site', max_length=20, verbose_name='Источник оприходования'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('telegram', 'telegram')], default='site', max_length=20, verbose_name='Источник списания'),
        ),
    ]
