# Generated by Django 4.2.6 on 2024-03-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_order_product_modifications_alter_inventory_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_modifications',
        ),
    ]
