# Generated by Django 4.2.6 on 2024-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(max_length=200, verbose_name='Связь с клиентом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(max_length=200, verbose_name='Способ доставки'),
        ),
    ]
