# Generated by Django 4.2.6 on 2024-04-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_order_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collage_image',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images/', verbose_name='Коллаж изображений'),
        ),
    ]
