# Generated by Django 4.2.6 on 2024-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя и Фамилия')),
                ('text', models.TextField(blank=True, verbose_name='Информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('receipt_issued', models.BooleanField(default=False, verbose_name='Пробит ли чек')),
                ('ttn', models.CharField(blank=True, max_length=30, verbose_name='Номер ТТН')),
                ('shipped_to_customer', models.BooleanField(default=False, verbose_name='Отправлено ли покупателю')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
    ]
