# Generated by Django 4.2.6 on 2023-11-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_rename_username_telegramuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('telegram', 'telegram')], default='site', max_length=20, verbose_name='Источник продажи'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('telegram', 'telegram')], default='site', max_length=20, verbose_name='Источник продажи'),
        ),
    ]
