# Generated by Django 4.2.6 on 2024-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='drop',
            field=models.BooleanField(default=False, verbose_name='Дропшипинг ли'),
        ),
    ]
