# Generated by Django 4.2.6 on 2024-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_preorder_drop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='drop',
            field=models.BooleanField(default=False, verbose_name='Дроп ли'),
        ),
    ]
