# Generated by Django 4.2.6 on 2024-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_preorder_drop_alter_preorder_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус посылки'),
        ),
    ]
