# Generated by Django 4.2.6 on 2024-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_preorder_payment_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('telegram', 'telegram')], default='site', max_length=20, verbose_name='Источник возврата'),
        ),
    ]
