# Generated by Django 4.2.6 on 2024-09-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_return_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
