# Generated by Django 4.2.6 on 2024-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='is_bulk_update',
            field=models.BooleanField(default=False),
        ),
    ]
