# Generated by Django 4.2.6 on 2024-09-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_preorder_is_bulk_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='is_bulk_update',
        ),
    ]
